### ISSUE TITLE
Not showing up in ZP after installation.

### ISSUE THREAD

**Issue by TheBox193** [deanmoses/zenphoto-json-rest-api#13]
I'm not sure if I'm misunderstanding the install instructions, but it seems pretty straight forward.

I placed `json_rest_api.php` and `json_rest_api` folder in `/plugins/json_rest_api/` with `644` permissions. But I'm not seeing it show up in in the `Plugins > Development` or `Plugins > All`.

My system info:
```
Zenphoto version 1.4.14 [f5b47da52f] (Official build)
Current locale setting: en_US.UTF8
PHP version: 5.5.37
```

Is there something obvious I'm missing?

**Comment by deanmoses** [comment]
Put `json_rest_api.php` in `/plugins/`, not `/plugins/json_rest_api/`

**Comment by TheBox193** [comment]
:man_facepalming:
Sigh, thanks. Figured it followed the pattern of the others plugins, my mistake.
