### ISSUE TITLE
Gettext for error messages

### ISSUE THREAD

**Issue by acrylian** [deanmoses/zenphoto-json-rest-api#4]
Since it is a non official plugin, that would need to be the plugin way using `gettext_pl`. Not pressing needed as there are only a few strings to translate yet.

**Comment by deanmoses** [comment]
Sorry, didn't see you had assigned this to yourself.

**Comment by acrylian** [comment]
No problem. To allow plugin based translation we will also need to add an accompanying folder where the translation files are stored. I can setup that and add at least a German translation.
