### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by acrylian** [deanmoses/zenphoto-json-rest-api#6]
On large sites getting data for all albums or even the full album tree may overload servers. Zenphoto generate pagination anyway. 

So we could have the main gallery index (page 1 - top level albums) and following that the page 1 of any album page return paged results or not by option. (Similar for Zenpage articles, categories later on). Same on further album levels.

I suggest an additional parameter `&paged=0|1` to disable/enable paginated results.

Any further page like page 2 could by default also return just data for that page unless `paged` is set otherwise.

Furthermore, the `deep` parameter to enable the full tree could be replace by a parameter `level`. -

- `level=0` could be all levels (former deep)
- `level=1` current level
- `level=2`current level plus next sub level
- and so on

**Comment by deanmoses** [comment]
The plugin definitely needs to take advantage of Zenphoto's pagination.

I *think* you're proposing a `page` parameter:
`myAlbum/?json&page=1` first page
`myAlbum/?json&page=2` second page...

I like that... but I'm not sure why we'd also need the `paged=1|0` parameter. Wouldn't the absence of `page` return the full, unpaged album?

As far as `level` instead of `deep`:  sure.

**Comment by acrylian** [comment]
No, I  was actually not proposing a api page parameter. Since the api hooks into the normal theme page urls, we already have a page parameter to use:
`myAlbum/` is the same as `myAlbum/page/1`. Internally it is always page 1 if no page is set explicitly. So `paged` could be used to disable that behaviour and get all albums like now.

Another idea would be: Even if we get the full album list using `paged=0` it could be multidimensional result storing paged results to make it easier to buld custom things possibly. Like this:
`$albums = array(
       1 => array(
              'album1',
              'album2'),
      2 => array(
              'album3',
              'album4')
);`

But I don't want to overcomplicate any results.

**Comment by deanmoses** [comment]
It now respects Zenphoto's normal album and search pagination, and there's a `pagination=off` parameter.  Upated the docs https://github.com/deanmoses/zenphoto-json-rest-api/blob/master/README.md
